server.port=8081
logging.level.org.atmosphere = warn
spring.mustache.check-template-location = false

spring.datasource.url=jdbc:postgresql://localhost:5432/prism_dash
spring.datasource.username=bms
spring.datasource.password=Pr1smDa$h
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.client.registration.keycloak.client-id=prism-dashboard
spring.security.oauth2.client.registration.keycloak.client-secret=wpGTgfgFppgtYKdc7iFRa7ZalmbL8FM7
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8843/realms/prism

#smtp info, declare app pass (keep it out of git) - will eventually be wired within postfix
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=support@prismclinicalimaging.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

prism.external-base-url=http://localhost:8081

#storage designation for files
prism.files.storage-path=C:/Dev/prism-dashboard-data
#upping the allowed amount for patient file uploading here, I think its 5mb by default, but IMEKA typically runs 20-25? Eh, give it 100.
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Launch the default browser when starting the application in development mode
vaadin.launch-browser=true

#pt file upload configs
prism.files.allowed-extensions=pdf,docx,xlsx,csv,jpg,jpeg,png
prism.files.max-size-mb=100
