package com.bms.processing.model;

public enum CaseIssueType {
    MISSING_DATA,
    INADEQUATE_SCAN_DATA,
    CORRUPT_DICOM,
    MISSING_STUDY_INFORMATION,
    VENDOR_FAILURE,
    QA_ARTIFACT,
    IMAGE_QUALITY,
    REPORT_CORRECTION,
    ADMINISTRATIVE,
    OTHER
}