-- Prism Dashboard PostgreSQL Schema
-- Updated to reflect the current development schema as of 2026-08-25.
-- Intended for creation of a fresh Prism Dashboard database.

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

SET search_path = public;

-- ============================================================
-- CASE RECORD
-- ============================================================

CREATE TABLE public.case_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    completed_date TIMESTAMP(6) WITHOUT TIME ZONE,
    duramap_sent_date DATE,
    duramap_status VARCHAR(255),
    final_outcome VARCHAR(255),
    imeka_sent_date DATE,
    imeka_status VARCHAR(255),
    neuroreader_sent_date DATE,
    neuroreader_status VARCHAR(255),
    notes TEXT,
    patient_id VARCHAR(255),
    patient_last_name VARCHAR(255),
    patient_status VARCHAR(255),
    site_name VARCHAR(255),
    processing_outcome VARCHAR(255),
    duramap_error_note TEXT,
    imeka_error_note TEXT,
    neuroreader_error_note TEXT,
    images_received_date DATE,
    patient_first_name VARCHAR(255),
    date_of_birth DATE,
    date_scanned DATE,
    funder VARCHAR(255),
    intake_sheet_done BOOLEAN,
    intake_sheet_sent BOOLEAN,
    processed_date TIMESTAMP(6) WITHOUT TIME ZONE,
    owner_group VARCHAR(255),
    assigned_to_user VARCHAR(255),
    imeka_uploaded_date TIMESTAMP WITHOUT TIME ZONE,
    sex VARCHAR(255),
    final_workflow_notes TEXT,
    study_instance_uid VARCHAR(255),
    accession_number VARCHAR(255),
    dicom_linked BOOLEAN DEFAULT FALSE,
    invoice_sent_date DATE,

    CONSTRAINT case_record_duramap_status_check CHECK (
        duramap_status IN ('NOT_SENT', 'SENT', 'COMPLETED', 'UPLOADED', 'ERROR')
    ),
    CONSTRAINT case_record_final_outcome_check CHECK (
        final_outcome IN (
            'COMPLETED',
            'COMPLETED_WITH_THIRD_PARTY_ERRORS',
            'COMPLETED_WITH_ERRORS',
            'UNCOMPLETED',
            'RESCAN_NEEDED'
        )
    ),
    CONSTRAINT case_record_imeka_status_check CHECK (
        imeka_status IN ('NOT_SENT', 'SENT', 'COMPLETED', 'UPLOADED', 'ERROR')
    ),
    CONSTRAINT case_record_neuroreader_status_check CHECK (
        neuroreader_status IN ('NOT_SENT', 'SENT', 'COMPLETED', 'UPLOADED', 'ERROR')
    ),
    CONSTRAINT case_record_patient_status_check CHECK (
        patient_status IN (
            'UPCOMING',
            'VERIFYING',
            'ACQUIRED',
            'PROCESSING',
            'PROCESSED',
            'COMPLETED',
            'ON_HOLD',
            'MISSING_DATA',
            'RESCAN_REQUIRED',
            'REPORT_CORRECTION_REQUIRED',
            'CANCELLED'
        )
    ),
    CONSTRAINT case_record_processing_outcome_check CHECK (
        processing_outcome IN ('PENDING', 'UPLOADED', 'DURAMAP_SENT')
    )
);

ALTER TABLE public.case_record OWNER TO bms;

-- ============================================================
-- SITES
-- ============================================================

CREATE TABLE public.site (
    id BIGSERIAL PRIMARY KEY,
    facility_name VARCHAR(255),
    address VARCHAR(255),
    address_line_1 VARCHAR(255),
    address_line_2 VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(10),
    zip_code VARCHAR(20),
    primary_contact VARCHAR(255),
    transfer_method VARCHAR(255),
    imeka_certified BOOLEAN,
    scanner_brand VARCHAR(255),
    magnet_strength VARCHAR(255),
    active BOOLEAN DEFAULT TRUE,
    notes TEXT
);

ALTER TABLE public.site OWNER TO bms;
ALTER SEQUENCE public.site_id_seq OWNER TO bms;

CREATE TABLE public.site_contact (
    id BIGSERIAL PRIMARY KEY,
    site_id BIGINT NOT NULL,
    contact_name VARCHAR(255),
    title VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(50),

    CONSTRAINT fk_site_contact_site
        FOREIGN KEY (site_id)
        REFERENCES public.site(id)
        ON DELETE CASCADE
);

ALTER TABLE public.site_contact OWNER TO bms;
ALTER SEQUENCE public.site_contact_id_seq OWNER TO bms;

-- ============================================================
-- AUDIT EVENTS
-- ============================================================

CREATE TABLE public.audit_event (
    id BIGSERIAL PRIMARY KEY,
    case_record_id BIGINT,
    event_type VARCHAR(255),
    message TEXT,
    old_value TEXT,
    new_value TEXT,
    created_by VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE
);

ALTER TABLE public.audit_event OWNER TO bms;
ALTER SEQUENCE public.audit_event_id_seq OWNER TO bms;

-- ============================================================
-- CENTRALIZED CASE ISSUES
-- ============================================================

CREATE TABLE public.case_issue (
    id BIGSERIAL PRIMARY KEY,
    case_record_id BIGINT NOT NULL,
    issue_type VARCHAR(100) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    blocking BOOLEAN NOT NULL DEFAULT FALSE,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    created_by VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_by VARCHAR(255),
    resolved_at TIMESTAMP WITHOUT TIME ZONE,
    resolution_note TEXT,

    CONSTRAINT fk_case_issue_case_record
        FOREIGN KEY (case_record_id)
        REFERENCES public.case_record(id)
        ON DELETE CASCADE
);

ALTER TABLE public.case_issue OWNER TO bms;
ALTER SEQUENCE public.case_issue_id_seq OWNER TO bms;

-- ============================================================
-- NOTIFICATIONS / EMAIL
-- ============================================================

CREATE TABLE public.notification_recipient (
    id BIGSERIAL PRIMARY KEY,
    group_name VARCHAR(100) NOT NULL,
    email_address VARCHAR(255) NOT NULL,
    recipient_type VARCHAR(10) NOT NULL DEFAULT 'TO',
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);

ALTER TABLE public.notification_recipient OWNER TO bms;
ALTER SEQUENCE public.notification_recipient_id_seq OWNER TO bms;

CREATE TABLE public.email_template (
    id BIGSERIAL PRIMARY KEY,
    template_key VARCHAR(100) UNIQUE NOT NULL,
    subject VARCHAR(500) NOT NULL,
    body TEXT NOT NULL,
    enabled BOOLEAN DEFAULT TRUE
);

ALTER TABLE public.email_template OWNER TO bms;
ALTER SEQUENCE public.email_template_id_seq OWNER TO bms;

-- ============================================================
-- DICOM CONFIGURATION
-- ============================================================

CREATE TABLE public.dicom_config (
    id BIGSERIAL PRIMARY KEY,
    config_name VARCHAR(255) NOT NULL,
    remote_ae_title VARCHAR(64) NOT NULL,
    remote_host VARCHAR(255) NOT NULL,
    remote_port INTEGER NOT NULL,
    local_ae_title VARCHAR(64) NOT NULL,
    retrieve_ae_title VARCHAR(64),
    retrieve_port INTEGER DEFAULT 11113,
    storage_path VARCHAR(1000) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE
);

ALTER TABLE public.dicom_config OWNER TO bms;
ALTER SEQUENCE public.dicom_config_id_seq OWNER TO bms;

-- ============================================================
-- PATIENT FILES
-- ============================================================

CREATE TABLE public.patient_file (
    id BIGSERIAL PRIMARY KEY,
    case_record_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    original_file_name VARCHAR(255),
    file_type VARCHAR(100) NOT NULL,
    source VARCHAR(100) NOT NULL,
    file_date DATE,
    content_type VARCHAR(255),
    file_size BIGINT,
    storage_path VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_patient_file_case_record
        FOREIGN KEY (case_record_id)
        REFERENCES public.case_record(id)
        ON DELETE CASCADE
);

ALTER TABLE public.patient_file OWNER TO bms;
ALTER SEQUENCE public.patient_file_id_seq OWNER TO bms;

-- ============================================================
-- PATIENT TICKETS
-- ============================================================

CREATE TABLE public.patient_ticket (
    id BIGSERIAL PRIMARY KEY,
    case_record_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'OPEN',
    assigned_to VARCHAR(100),
    created_by VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT fk_patient_ticket_case_record
        FOREIGN KEY (case_record_id)
        REFERENCES public.case_record(id)
        ON DELETE CASCADE
);

ALTER TABLE public.patient_ticket OWNER TO bms;
ALTER SEQUENCE public.patient_ticket_id_seq OWNER TO bms;

CREATE TABLE public.patient_ticket_message (
    id BIGSERIAL PRIMARY KEY,
    patient_ticket_id BIGINT NOT NULL,
    message TEXT NOT NULL,
    created_by VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_patient_ticket_message_ticket
        FOREIGN KEY (patient_ticket_id)
        REFERENCES public.patient_ticket(id)
        ON DELETE CASCADE
);

ALTER TABLE public.patient_ticket_message OWNER TO bms;
ALTER SEQUENCE public.patient_ticket_message_id_seq OWNER TO bms;

-- ============================================================
-- SECURE FILE SHARING
-- ============================================================

CREATE TABLE public.case_secure_share (
    id BIGSERIAL PRIMARY KEY,
    case_record_id BIGINT NOT NULL,
    recipient_name VARCHAR(255) NOT NULL,
    recipient_email VARCHAR(255) NOT NULL,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    access_code_hash VARCHAR(255),
    allow_view BOOLEAN NOT NULL DEFAULT TRUE,
    allow_download BOOLEAN NOT NULL DEFAULT TRUE,
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITHOUT TIME ZONE,
    max_downloads INTEGER,
    download_count INTEGER NOT NULL DEFAULT 0,
    created_by VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_accessed_at TIMESTAMP WITHOUT TIME ZONE,
    access_code_expires_at TIMESTAMP WITHOUT TIME ZONE,
    access_code_attempts INTEGER NOT NULL DEFAULT 0,
    verified_at TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT fk_secure_share_case
        FOREIGN KEY (case_record_id)
        REFERENCES public.case_record(id)
        ON DELETE CASCADE
);

ALTER TABLE public.case_secure_share OWNER TO bms;
ALTER SEQUENCE public.case_secure_share_id_seq OWNER TO bms;

CREATE TABLE public.case_secure_share_file (
    secure_share_id BIGINT NOT NULL,
    patient_file_id BIGINT NOT NULL,

    CONSTRAINT case_secure_share_file_pkey
        PRIMARY KEY (secure_share_id, patient_file_id),

    CONSTRAINT fk_secure_share_file_share
        FOREIGN KEY (secure_share_id)
        REFERENCES public.case_secure_share(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_secure_share_file_patient_file
        FOREIGN KEY (patient_file_id)
        REFERENCES public.patient_file(id)
        ON DELETE CASCADE
);

ALTER TABLE public.case_secure_share_file OWNER TO bms;

-- ============================================================
-- END OF SCHEMA
-- ============================================================
