--
-- PostgreSQL database dump
--

\restrict sZog6QCZw02TWK1yAgc8GXMSv2gNAOzH1CRMzgzbWHmKSfSUKzIFrcchREBybaZ

-- Dumped from database version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: bms
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO bms;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: case_record; Type: TABLE; Schema: public; Owner: bms
--

CREATE TABLE public.case_record (
    id bigint NOT NULL,
    completed_date timestamp(6) without time zone,
    duramap_sent_date date,
    duramap_status character varying(255),
    final_outcome character varying(255),
    imeka_sent_date date,
	imeka_uploaded_date timestamp,
    imeka_status character varying(255),
    neuroreader_sent_date date,
    neuroreader_status character varying(255),
    notes text,
    patient_id character varying(255),
    study_instance_uid character varying(255),
    accession_number character varying(255),
    dicom_linked boolean DEFAULT false,
    patient_last_name character varying(255),
    patient_status character varying(255),
    site_name character varying(255),
	owner_group character varying(255),
    assigned_to_user character varying(255),
    processing_outcome character varying(255),
    duramap_error_note text,
    imeka_error_note text,
    final_workflow_notes text,
    neuroreader_error_note text,
    images_received_date date,
    patient_first_name character varying(255),
    date_of_birth date,
	sex character varying(10),
    date_scanned date,
    funder character varying(255),
    intake_sheet_done boolean,
    intake_sheet_sent boolean,
    invoice_sent boolean,
    processed_date timestamp(6) without time zone,
    CONSTRAINT case_record_duramap_status_check CHECK (((duramap_status)::text = ANY ((ARRAY['NOT_SENT'::character varying, 'SENT'::character varying, 'COMPLETED'::character varying, 'UPLOADED'::character varying, 'ERROR'::character varying])::text[]))),
    CONSTRAINT case_record_final_outcome_check CHECK (((final_outcome)::text = ANY ((ARRAY['COMPLETED'::character varying, 'COMPLETED_WITH_THIRD_PARTY_ERRORS'::character varying, 'COMPLETED_WITH_ERRORS'::character varying, 'UNCOMPLETED'::character varying, 'RESCAN_NEEDED'::character varying])::text[]))),
    CONSTRAINT case_record_imeka_status_check CHECK (((imeka_status)::text = ANY ((ARRAY['NOT_SENT'::character varying, 'SENT'::character varying, 'COMPLETED'::character varying, 'UPLOADED'::character varying, 'ERROR'::character varying])::text[]))),
    CONSTRAINT case_record_neuroreader_status_check CHECK (((neuroreader_status)::text = ANY ((ARRAY['NOT_SENT'::character varying, 'SENT'::character varying, 'COMPLETED'::character varying, 'UPLOADED'::character varying, 'ERROR'::character varying])::text[]))),
    CONSTRAINT case_record_patient_status_check CHECK (((patient_status)::text = ANY ((ARRAY['UPCOMING'::character varying, 'VERIFYING'::character varying, 'ACQUIRED'::character varying, 'PROCESSING'::character varying, 'PROCESSED'::character varying, 'PROCESSED_WITH_ERRORS'::character varying, 'PROCESSED_WITH_THIRD_PARTY_ERRORS'::character varying, 'COMPLETED'::character varying, 'ERROR'::character varying])::text[]))),
    CONSTRAINT case_record_processing_outcome_check CHECK (((processing_outcome)::text = ANY ((ARRAY['PENDING'::character varying, 'UPLOADED'::character varying, 'DURAMAP_SENT'::character varying])::text[])))
);

-- Updated facility address entries 6042026

CREATE TABLE public.site (
    id BIGSERIAL PRIMARY KEY,
    facility_name character varying(255),

    address character varying(255),
    address_line_1 character varying(255),
    address_line_2 character varying(255),
    city character varying(100),
    state character varying(10),
    zip_code character varying(20),

    primary_contact character varying(255),
    transfer_method character varying(255),
    imeka_certified boolean,
    scanner_brand character varying(255),
    magnet_strength character varying(255),

    active boolean DEFAULT true,
    notes text
);

ALTER TABLE public.case_record OWNER TO bms;
ALTER TABLE public.site OWNER TO bms;

--
-- Name: case_record_id_seq; Type: SEQUENCE; Schema: public; Owner: bms
--

ALTER TABLE public.case_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.case_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Adding in audit event db table 06012026

CREATE TABLE audit_event (
    id BIGSERIAL PRIMARY KEY,
    case_record_id BIGINT,
    event_type character varying(255),
    message text,
    old_value text,
    new_value text,
    created_by character varying(255),
    created_at timestamp
);

-- This creates table for email recipients for SMTP sending

CREATE TABLE notification_recipient (
    id BIGSERIAL PRIMARY KEY,
    group_name character varying(100) NOT NULL,
    email_address character varying(255) NOT NULL,
    recipient_type character varying(10) NOT NULL DEFAULT 'TO',
    enabled boolean NOT NULL DEFAULT true
);

-- Table for site contacts

CREATE TABLE site_contact (
    id BIGSERIAL PRIMARY KEY,
    site_id BIGINT NOT NULL,
    contact_name VARCHAR(255),
	title VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(50),

    CONSTRAINT fk_site_contact_site
        FOREIGN KEY (site_id)
        REFERENCES site(id)
        ON DELETE CASCADE
);

-- Email template table
CREATE TABLE email_template (
    id BIGSERIAL PRIMARY KEY,
    template_key VARCHAR(100) UNIQUE NOT NULL,
    subject VARCHAR(500) NOT NULL,
    body TEXT NOT NULL,
    enabled BOOLEAN DEFAULT TRUE
);

CREATE TABLE dicom_config (
    id BIGSERIAL PRIMARY KEY,
    config_name VARCHAR(255) NOT NULL,
    remote_ae_title VARCHAR(64) NOT NULL,
    remote_host VARCHAR(255) NOT NULL,
    remote_port INTEGER NOT NULL,
    local_ae_title VARCHAR(64) NOT NULL,
    retrieve_ae_title VARCHAR(64),
	retrieve_port integer DEFAULT 11113,
    storage_path VARCHAR(1000) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE patient_file (
    id BIGSERIAL PRIMARY KEY,
    case_record_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    original_file_name VARCHAR(255),
    file_type VARCHAR(100) NOT NULL,
    source VARCHAR(100) NOT NULL,
    file_date DATE,
    content_type VARCHAR(255),
    file_size BIGINT,
    storage_path VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_patient_file_case_record
        FOREIGN KEY (case_record_id)
        REFERENCES case_record(id)
        ON DELETE CASCADE
);

CREATE TABLE patient_ticket (
    id BIGSERIAL PRIMARY KEY,
    case_record_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'OPEN',
    assigned_to VARCHAR(100),
    created_by VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_patient_ticket_case_record
        FOREIGN KEY (case_record_id)
        REFERENCES case_record(id)
        ON DELETE CASCADE
);

CREATE TABLE patient_ticket_message (
    id BIGSERIAL PRIMARY KEY,
    patient_ticket_id BIGINT NOT NULL,
    message TEXT NOT NULL,
    created_by VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_patient_ticket_message_ticket
        FOREIGN KEY (patient_ticket_id)
        REFERENCES patient_ticket(id)
        ON DELETE CASCADE
);

--
-- Name: case_record case_record_pkey; Type: CONSTRAINT; Schema: public; Owner: bms
--

ALTER TABLE ONLY public.case_record
    ADD CONSTRAINT case_record_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict sZog6QCZw02TWK1yAgc8GXMSv2gNAOzH1CRMzgzbWHmKSfSUKzIFrcchREBybaZ

